version: "3.9"
services:

  gateway:
    build: ./gateway

  user-service:
    build: ./user-service

  path-service:
    build: ./path-service

  resource-service:
    build: ./resource-service

  progress-service:
    build: ./progress-service

  ai-service:
    build: ./ai-service

  notification-service:
    build: ./notification-service

  frontend:
    build: ./frontend
